import { useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { GetServerSidePropsContext } from 'next';
import { RecordKeeper } from '../utils';
import styles from '../styles/Home.module.css'

export async function getServerSideProps({ req, res }: GetServerSidePropsContext) {
  const record = new RecordKeeper(req, res);

  return {
    props: {
      records: record.get()
    }, // will be passed to the page component as props
  }
}

interface HomeProps {
  records: HistoricalRecord[]
}

export default function Home({
  records
}: HomeProps) {
  const [history] = useState<HistoricalRecord[]>([...records])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to USD to BRL Monitor
        </h1>
        {JSON.stringify(history)}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
